project_name: Versioneer
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
builds:
- goos:
    - darwin
    - linux
  goarch:
    - amd64
  env:
    - CGO_ENABLED=0
  # Custom ldflags templates.
  # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
  ldflags:
    - -s -w
    - -X {{ .Env.Repo }}/cmd.builtBy=goreleaser
    - -X {{ .Env.Repo }}/cmd.commit={{.ShortCommit}}
    - -X {{ .Env.Repo }}/cmd.date={{.Date}}
    - -X {{ .Env.Repo }}/cmd.version={{.Version}}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
  # The following will prevent the readme from being added to the archive
  files:
  - none*
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: TheWolfNL
    name: Versioneer